vendor/linux-${DEB_HOST_GNU_CPU}/langpack-es-AR@firefox.mozilla.org.xpi usr/lib/firefox/distribution/extensions
vendor/linux-${DEB_HOST_GNU_CPU}/langpack-es-CL@firefox.mozilla.org.xpi usr/lib/firefox/distribution/extensions
vendor/linux-${DEB_HOST_GNU_CPU}/langpack-es-ES@firefox.mozilla.org.xpi usr/lib/firefox/distribution/extensions
vendor/linux-${DEB_HOST_GNU_CPU}/langpack-es-MX@firefox.mozilla.org.xpi usr/lib/firefox/distribution/extensions
